### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by PCH-Tech** [microsoft/GitHub-Copilot-for-Azure#59] opened 2024-12-21 09:39 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: @azure.didSignOut
Error type: Error
Error Message: Unable to write into user settings because the file has unsaved changes. Please save the user settings file first and then try again.

Version: 0.3.61
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code - Insiders
Product Version: 1.97.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
dat.y workbench.desktop.main.js:3112:6643
dat.E workbench.desktop.main.js:3112:9548
dat.n workbench.desktop.main.js:3112:3863
Object.factory workbench.desktop.main.js:3112:3763
Dw.j workbench.desktop.main.js:31:74338
vscode-file:/workbench.desktop.main.js:31:74250
Dw.queue workbench.desktop.main.js:31:74192
dat.writeConfiguration workbench.desktop.main.js:3112:3732
oFs.Hb workbench.desktop.main.js:3112:42111
```

</details>

**Comment by MRayermannMSFT** [comment] 2024-12-23 16:51
Duplicate of #58 , please refer to that issue for help/discussion.

**Closed by MRayermannMSFT** 2024-12-23 16:51 UTC
