### ISSUE TITLE
Can't use ephemeral kql file as reference for follow-up question

### ISSUE THREAD

**Issue by pamelafox** [microsoft/GitHub-Copilot-for-Azure#35] opened 2024-12-05 00:44 UTC
Type: <b>Bug</b>

After getting a kql resource from a logs question, I opened that kql and tried to ask a question to refine the query, but I get an ENOPRO error, presumably because the kql is in an ephemeral location.

"ENOPRO: No file system provider found for resource 'azuretoolsd32474:/0abcbb12474d34b5/Query-Table-ContainerAppConsoleLogs_CL.kql'"

Extension version: 0.3.7
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|23, 13, 11|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 62586060-13a2-4d6f-9b3f-4b1de1d548e4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
h409b430:31179529

```

</details>

**Comment by pamelafox** [comment] 2024-12-05 00:45
![Image](https://github.com/user-attachments/assets/f7a4a5cc-34a9-4f18-9d21-6be7efb3d256)

**Comment by bwateratmsft** [comment] 2024-12-05 14:40
@pamelafox does this still reproduce in the latest version (0.3.42)? I think it's probably fixed in that version.

**Comment by pamelafox** [comment] 2024-12-05 17:09
I've updated, but now it just won't answer the question any more:

"
@azure query the logs for container app pf-chatapp-nhqj4jtf-ca in subscription 77d8a3d0-8b18-47e9-b773-08bee327bb4a

Azure (Preview)
I was unable to determine the Azure app to query the logs for the container app pf-chatapp-nhqj4jtf-ca. Please ensure that the app name and subscription ID are correct and that you have the necessary permissions.

Responses are currently scoped to the CA-Python-2502 tenant. [Select a different tenant](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html).
"

The tenant is correct and the app name matches what I see in Portal and subscription ID matches as well, so am not sure what's happening. I think this happened yesterday too so not necessarily related to the update. Maybe the auth token has expired?

**Comment by bwateratmsft** [comment] 2024-12-05 17:10
Can you file a new issue for that? I'll resolve this one since it sounds like it's fixed.

**Closed by bwateratmsft** 2024-12-05 17:10 UTC
Labels: info-needed
