### ISSUE TITLE
pkill -f node

### ISSUE THREAD

**Issue by erenuludemir** [microsoft/GitHub-Copilot-for-Azure#62] opened 2024-12-23 19:59 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azextAgent.activate
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.3.61
OS: darwin
OS Release: 24.3.0
Product: Visual Studio Code - Insiders
Product Version: 1.97.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
dat.y workbench.desktop.main.js:3112:6643
dat.o workbench.desktop.main.js:3112:4111
dat.n workbench.desktop.main.js:3112:4002
async Object.factory workbench.desktop.main.js:3112:3752
```

</details>

**Comment by JasonYeMSFT** [comment] 2024-12-26 17:15
@erenuludemir The error may be caused by a corrupted settings file. Could you use F1 > Open User Settings (JSON) to open the settings file as a text file and see if you can find any issues in it?

**Comment by JasonYeMSFT** [comment] 2024-12-30 18:23
Duplicate of #58

**Closed by JasonYeMSFT** 2024-12-30 18:23 UTC
Labels: duplicate
