### ISSUE TITLE
RUN

### ISSUE THREAD

**Issue by erenuludemir** [microsoft/GitHub-Copilot-for-Azure#61] opened 2024-12-23 15:50 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azextAgent.activate
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.3.61
OS: darwin
OS Release: 24.3.0
Product: Visual Studio Code - Insiders
Product Version: 1.97.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
dat.y workbench.desktop.main.js:3112:6643
dat.o workbench.desktop.main.js:3112:4111
dat.n workbench.desktop.main.js:3112:4002
async Object.factory workbench.desktop.main.js:3112:3752
```

</details>

**Comment by MRayermannMSFT** [comment] 2024-12-23 16:52
Duplicate of https://github.com/microsoft/GitHub-Copilot-for-Azure/issues/58 , please refer to that issue for help/discussion.

**Closed by MRayermannMSFT** 2024-12-23 16:52 UTC
