### ISSUE TITLE
@azure /cost - error

### ISSUE THREAD

**Issue by nats2025** [microsoft/GitHub-Copilot-for-Azure#22] opened 2024-11-15 14:42 UTC
@azure /cost what is the cost incurred for the month of oct 2024, Getting below error after entering user name and password for Azure account 

An error occurred while trying to determine if you have access to @azure: The call to the access check endpoint failed.

#21

**Comment by bwateratmsft** [comment] 2024-11-15 15:28
Resolving this one as a duplicate of #21

**Closed by bwateratmsft** 2024-11-15 15:28 UTC
